# Tutorial Part 2: Deep Learning Libraries
In this tutorial, you'll get familiar with the most popular deep learning libraries

## Keras
https://keras.io/

In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Activation

Using TensorFlow backend.


In [2]:
# define the model
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=100))
model.add(Dense(1, activation='sigmoid'))

In [3]:
# compile accepts the optimizer and the loss function
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [4]:
# training data
data = np.random.random((1000, 100)).astype(np.float32)
labels = np.random.randint(2, size=(1000, 1)).astype(np.float32)

In [5]:
data.shape

(1000, 100)

In [6]:
data[:3 :10]

array([[0.46766102, 0.24123445, 0.08452388, 0.3666759 , 0.5820863 ,
        0.02717233, 0.8092726 , 0.693232  , 0.30956918, 0.5262542 ,
        0.40517676, 0.07081285, 0.7481114 , 0.30779898, 0.82729685,
        0.23595078, 0.6501258 , 0.98552865, 0.52228624, 0.5963983 ,
        0.424813  , 0.54538333, 0.74023277, 0.5186164 , 0.31013143,
        0.67367864, 0.46165305, 0.6002972 , 0.78533745, 0.30551317,
        0.9495062 , 0.54857415, 0.31167874, 0.6954676 , 0.34788182,
        0.57518405, 0.10705369, 0.60875726, 0.04705686, 0.92498744,
        0.63246715, 0.6264184 , 0.24140006, 0.47684294, 0.80372345,
        0.34266523, 0.34900242, 0.6545629 , 0.01746015, 0.6232982 ,
        0.32974026, 0.35938972, 0.01104516, 0.24891818, 0.6058826 ,
        0.37562242, 0.75703883, 0.5283604 , 0.5472243 , 0.90663797,
        0.02140716, 0.1939004 , 0.92440516, 0.85662585, 0.60428405,
        0.81388116, 0.72490865, 0.39498776, 0.29004273, 0.40608948,
        0.27011403, 0.47289285, 0.9261094 , 0.13

In [7]:
labels.shape

(1000, 1)

In [8]:
labels[:10]

array([[1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.]], dtype=float32)

In [9]:
model.fit(data, labels, epochs=10, batch_size=32)

Epoch 1/10
1000/1000 [==============================] - 0s 175us/step - loss: 0.7167 - acc: 0.4690
Epoch 2/10
1000/1000 [==============================] - 0s 30us/step - loss: 0.7037 - acc: 0.5150
Epoch 3/10
1000/1000 [==============================] - 0s 30us/step - loss: 0.6977 - acc: 0.5090
Epoch 4/10
1000/1000 [==============================] - 0s 32us/step - loss: 0.6918 - acc: 0.5270
Epoch 5/10
1000/1000 [==============================] - 0s 32us/step - loss: 0.6897 - acc: 0.5450
Epoch 6/10
1000/1000 [==============================] - 0s 30us/step - loss: 0.6896 - acc: 0.5450
Epoch 7/10
1000/1000 [==============================] - 0s 34us/step - loss: 0.6847 - acc: 0.5460
Epoch 8/10
1000/1000 [==============================] - 0s 31us/step - loss: 0.6751 - acc: 0.5750
Epoch 9/10
1000/1000 [==============================] - 0s 32us/step - loss: 0.6728 - acc: 0.5890
Epoch 10/10
1000/1000 [==============================] - 0s 32us/step - loss: 0.6727 - acc: 0.5960


## Tensorflow
https://www.tensorflow.org/

In [10]:
import tensorflow as tf

### Introduction

In [11]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0)

In [12]:
a

<tf.Tensor 'Const:0' shape=() dtype=float32>

In [13]:
sess = tf.Session()

In [14]:
sess.run([a,b])

[3.0, 4.0]

In [15]:
c = a + b

In [16]:
c

<tf.Tensor 'add:0' shape=() dtype=float32>

In [17]:
sess.run(c)

7.0

In [18]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder = a + b

In [19]:
sess.run(adder, {a: 3, b:4})

7.0

In [20]:
sess.run(adder, {a: 10, b:20})

30.0

### The same model

In [21]:
inputs = tf.placeholder(tf.float32, shape=(None, 100))
targets = tf.placeholder(tf.float32, shape=(None, 1))

fc1 = tf.layers.dense(inputs, 32, activation=tf.nn.relu)
outputs = tf.layers.dense(fc1, 1, activation=None)

outputs_sigmoid = tf.nn.sigmoid(outputs)

In [22]:
inputs

<tf.Tensor 'Placeholder_2:0' shape=(?, 100) dtype=float32>

In [23]:
fc1

<tf.Tensor 'dense/Relu:0' shape=(?, 32) dtype=float32>

In [24]:
outputs

<tf.Tensor 'dense_3/BiasAdd:0' shape=(?, 1) dtype=float32>

In [25]:
loss = tf.losses.sigmoid_cross_entropy(targets, outputs)
accuracy = tf.reduce_mean(tf.to_float(tf.equal(targets, tf.to_float(outputs_sigmoid > 0.5))))

In [26]:
optimizer = tf.train.AdamOptimizer(0.001)
train = optimizer.minimize(loss)

In [27]:
init = tf.global_variables_initializer()
sess.run(init)

In [29]:
nb_epochs = 20
batch_size = 64
nb_batches = len(data) // batch_size
for epoch in range(nb_epochs):
    accuracies = []
    losses = []
    for batch_idx in range(nb_batches):
        batch_start = batch_idx * batch_size
        batch_end = batch_start + batch_size

        batch_inputs = data[batch_start:batch_end]
        batch_targets = labels[batch_start:batch_end]       
      
        _, loss_value, accuracy_value = sess.run(
            [train, loss, accuracy], {inputs: batch_inputs, targets: batch_targets}
        )
        losses.append(loss_value)        
        accuracies.append(accuracy_value)
        
    accuracy_value = np.mean(accuracies)
    loss_value = np.mean(loss_value)    
    print(f'Epoch: {epoch}, loss: {loss_value:.3f}, accuracy: {accuracy_value:.3f}')

Epoch: 0, loss: 0.650, accuracy: 0.675
Epoch: 1, loss: 0.650, accuracy: 0.682
Epoch: 2, loss: 0.646, accuracy: 0.685
Epoch: 3, loss: 0.645, accuracy: 0.692
Epoch: 4, loss: 0.642, accuracy: 0.693
Epoch: 5, loss: 0.639, accuracy: 0.697
Epoch: 6, loss: 0.637, accuracy: 0.704
Epoch: 7, loss: 0.635, accuracy: 0.706
Epoch: 8, loss: 0.633, accuracy: 0.714
Epoch: 9, loss: 0.630, accuracy: 0.714
Epoch: 10, loss: 0.627, accuracy: 0.718
Epoch: 11, loss: 0.626, accuracy: 0.725
Epoch: 12, loss: 0.622, accuracy: 0.724
Epoch: 13, loss: 0.620, accuracy: 0.731
Epoch: 14, loss: 0.619, accuracy: 0.734
Epoch: 15, loss: 0.617, accuracy: 0.735
Epoch: 16, loss: 0.615, accuracy: 0.742
Epoch: 17, loss: 0.612, accuracy: 0.744
Epoch: 18, loss: 0.609, accuracy: 0.750
Epoch: 19, loss: 0.606, accuracy: 0.753


Note that there's also a `tf.estimator` API that makes the training a little bit simplier

## PyTorch
https://pytorch.org/

In [32]:
import itertools

In [33]:
import torch
import torch.nn.functional as F
import torch.utils.data

from sklearn.metrics import accuracy_score

### Introduction

In [34]:
a = torch.ones(5)

In [35]:
a

tensor([1., 1., 1., 1., 1.])

In [36]:
b = a + 10

In [37]:
b

tensor([11., 11., 11., 11., 11.])

### The same model

In [38]:
class Net(torch.nn.Module):
    def __init__(self, input_size, hidden_size=32):
        super().__init__()
        
        self.fc1 = torch.nn.Linear(100, hidden_size)
        self.fc2 = torch.nn.Linear(hidden_size, 1)
        
    def forward(self, inputs):
        hidden = F.relu(self.fc1(inputs))
        outputs = self.fc2(hidden)
        
        outputs = outputs
        return outputs

In [52]:
model = Net(input_size=data.shape[1])

In [53]:
model

Net(
  (fc1): Linear(in_features=100, out_features=32, bias=True)
  (fc2): Linear(in_features=32, out_features=1, bias=True)
)

In [54]:
model(torch.rand(4, 100))

tensor([[0.1069],
        [0.1112],
        [0.0593],
        [0.1342]], grad_fn=<AddmmBackward>)

In [55]:
model = model.cuda()

In [56]:
dataset = torch.utils.data.TensorDataset(torch.from_numpy(data), torch.from_numpy(labels))
data_loader = torch.utils.data.DataLoader(dataset, batch_size=batch_size, shuffle=True)

In [57]:
len(dataset[0])

2

In [58]:
dataset[0][0][:10]

tensor([0.4677, 0.2412, 0.0845, 0.3667, 0.5821, 0.0272, 0.8093, 0.6932, 0.3096,
        0.5263])

In [59]:
dataset[0][1]

tensor([1.])

In [60]:
criterion = torch.nn.BCEWithLogitsLoss().cuda()
optimizer = torch.optim.Adam(model.parameters())

In [61]:
nb_epochs = 20
batch_size = 64
nb_batches = len(data) // batch_size
for epoch in range(nb_epochs):
    accuracies = []
    losses = []
    for i, (inputs, targets) in enumerate(data_loader):
        optimizer.zero_grad()
        
        inputs = inputs.cuda()
        targets = targets.cuda()
        
        outputs = model(inputs)
        
        loss = criterion(outputs, targets)
        loss.backward()
        optimizer.step()        

        y_pred = (torch.sigmoid(outputs) > 0.5).data.cpu().numpy()
        y_true = targets.data.cpu().numpy()
        accuracy = accuracy_score(y_true, y_pred)
        
        losses.append(float(loss))
        accuracies.append(accuracy)
        
    accuracy = np.mean(accuracies)
    loss = np.mean(losses)    
    print(f'Epoch: {epoch}, loss: {loss:.3f}, accuracy: {accuracy:.3f}')        

Epoch: 0, loss: 0.695, accuracy: 0.485
Epoch: 1, loss: 0.693, accuracy: 0.502
Epoch: 2, loss: 0.691, accuracy: 0.521
Epoch: 3, loss: 0.690, accuracy: 0.550
Epoch: 4, loss: 0.688, accuracy: 0.548
Epoch: 5, loss: 0.688, accuracy: 0.564
Epoch: 6, loss: 0.686, accuracy: 0.553
Epoch: 7, loss: 0.683, accuracy: 0.552
Epoch: 8, loss: 0.681, accuracy: 0.611
Epoch: 9, loss: 0.680, accuracy: 0.554
Epoch: 10, loss: 0.680, accuracy: 0.587
Epoch: 11, loss: 0.674, accuracy: 0.583
Epoch: 12, loss: 0.670, accuracy: 0.653
Epoch: 13, loss: 0.666, accuracy: 0.614
Epoch: 14, loss: 0.665, accuracy: 0.631
Epoch: 15, loss: 0.662, accuracy: 0.629
Epoch: 16, loss: 0.659, accuracy: 0.651
Epoch: 17, loss: 0.654, accuracy: 0.639
Epoch: 18, loss: 0.656, accuracy: 0.596
Epoch: 19, loss: 0.648, accuracy: 0.651
